/**
 * Diagrams for the "Introduction to Programming" lesson.
 *
 * These are the lesson's own inline SVGs, ported 1:1 from the source course
 * (geometry, text and structure unchanged). The only edits are paint: the
 * source's hard-coded #111 / #555 / #999 / #9a4a1f are mapped onto the site's
 * theme tokens (`currentColor`, `--color-fd-muted-foreground`,
 * `--color-fd-ring`) so the diagrams read correctly in light and dark mode.
 *
 * Every <title>/aria-label is preserved for screen readers.
 */

const DIAGRAMS: Record<string, string> = {
  'itp-m1': `<svg viewBox="0 0 640 210" aria-label="Diagram from human idea to programming language to binary to computer action"><title>From idea to execution</title><rect x="10" y="60" width="130" height="80" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="75" y="90" text-anchor="middle" font-size="12">Your idea</text><text x="75" y="108" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">English steps</text><text x="75" y="122" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">Lego build</text><line x1="140" y1="100" x2="180" y2="100" stroke="currentColor" stroke-width="1.5"/><polygon points="180,94 192,100 180,106" fill="currentColor"/><rect x="192" y="60" width="140" height="80" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="262" y="90" text-anchor="middle" font-size="12">Language</text><text x="262" y="108" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">Python / Java / C</text><text x="262" y="122" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">interpreter</text><line x1="332" y1="100" x2="372" y2="100" stroke="currentColor" stroke-width="1.5"/><polygon points="372,94 384,100 372,106" fill="currentColor"/><rect x="384" y="60" width="120" height="80" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="444" y="92" text-anchor="middle" font-size="12" font-family="monospace">10101100</text><text x="444" y="110" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">machine code</text><line x1="504" y1="100" x2="544" y2="100" stroke="currentColor" stroke-width="1.5"/><polygon points="544,94 556,100 544,106" fill="currentColor"/><rect x="556" y="60" width="74" height="80" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="593" y="92" text-anchor="middle" font-size="12">Runs</text><text x="593" y="110" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">action</text><text x="75" y="170" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">human-readable</text><text x="262" y="170" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">middle layer</text><text x="444" y="170" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">hardware-readable</text></svg>`,

  'itp-m2': `<svg viewBox="0 0 640 200" aria-label="IDE loop diagram: edit, run, console"><title>Write-run-read loop</title><rect x="10" y="50" width="150" height="90" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="85" y="85" text-anchor="middle" font-size="12">1. Edit</text><text x="85" y="103" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">obey syntax</text><text x="85" y="117" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">IDE hints</text><rect x="245" y="50" width="150" height="90" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="320" y="85" text-anchor="middle" font-size="12">2. Run</text><text x="320" y="103" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">compile/interpret</text><text x="320" y="117" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">to machine code</text><rect x="480" y="50" width="150" height="90" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="555" y="85" text-anchor="middle" font-size="12">3. Console</text><text x="555" y="103" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">print(4+3) -&gt; 7</text><line x1="160" y1="95" x2="245" y2="95" stroke="currentColor" stroke-width="1.5"/><polygon points="245,89 257,95 245,101" fill="currentColor"/><line x1="395" y1="95" x2="480" y2="95" stroke="currentColor" stroke-width="1.5"/><polygon points="480,89 492,95 480,101" fill="currentColor"/><path d="M 555 140 C 400 180, 200 180, 85 140" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5" stroke-dasharray="5 4"/><text x="320" y="178" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">read output, fix, repeat</text></svg>`,

  'itp-m3': `<svg viewBox="0 0 640 220" aria-label="Variable boxes diagram"><title>Variables as boxes</title><g font-size="12"><rect x="20" y="40" width="150" height="110" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="95" y="30" text-anchor="middle">name : String</text><rect x="40" y="70" width="110" height="34" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5"/><text x="95" y="92" text-anchor="middle" font-size="11">no pointer exception</text><rect x="245" y="40" width="150" height="110" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="320" y="30" text-anchor="middle">age : int</text><rect x="265" y="70" width="110" height="34" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5"/><text x="320" y="92" text-anchor="middle" font-size="11">17 -&gt; 18</text><text x="320" y="130" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">reassign to update</text><rect x="470" y="40" width="150" height="110" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5" stroke-dasharray="5 4"/><text x="545" y="30" text-anchor="middle">input : String</text><text x="545" y="92" text-anchor="middle" font-size="11" fill="var(--color-fd-muted-foreground)">(empty)</text><text x="545" y="130" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">null if read now</text></g><text x="320" y="185" text-anchor="middle" font-size="11" fill="var(--color-fd-muted-foreground)">One label, one value. Read = look inside. Update = swap the paper.</text></svg>`,

  'itp-m4': `<svg viewBox="0 0 640 240" aria-label="Conditional branches and array indexes"><title>Branches and lists</title><polygon points="120,20 200,60 120,100 40,60" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="120" y="64" text-anchor="middle" font-size="11">condition?</text><rect x="20" y="130" width="180" height="46" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="110" y="150" text-anchor="middle" font-size="11">if-branch</text><text x="110" y="165" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">runs when true</text><rect x="240" y="130" width="180" height="46" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="330" y="150" text-anchor="middle" font-size="11">else-branch</text><text x="330" y="165" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">runs otherwise</text><line x1="80" y1="80" x2="40" y2="130" stroke="currentColor" stroke-width="1.5"/><line x1="160" y1="80" x2="360" y2="130" stroke="currentColor" stroke-width="1.5"/><g font-size="11"><rect x="460" y="30" width="150" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="535" y="50" text-anchor="middle">groceries[0]=milk</text><rect x="460" y="60" width="150" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="535" y="80" text-anchor="middle">groceries[1]=eggs</text><rect x="460" y="90" width="150" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="535" y="110" text-anchor="middle">groceries[2]=bread</text><text x="535" y="140" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">index: ordered slots</text></g></svg>`,

  'itp-m4-trace': `<svg viewBox="0 0 640 90" aria-label="Animated conditional trace"><title>Branch animation</title><rect x="10" y="20" width="150" height="50" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="85" y="50" text-anchor="middle" font-size="11">x % 2 == 0?</text><rect x="245" y="20" width="150" height="50" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="320" y="50" text-anchor="middle" font-size="11">print even</text><rect x="480" y="20" width="150" height="50" rx="8" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5"/><text x="555" y="50" text-anchor="middle" font-size="11">print odd</text><circle cx="170" cy="45" r="6" fill="currentColor"/></svg>`,

  'itp-m5': `<svg viewBox="0 0 640 210" aria-label="For loop stages diagram"><title>Loop stages</title><rect x="10" y="60" width="130" height="70" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="75" y="90" text-anchor="middle" font-size="11">start</text><text x="75" y="106" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">i = 0</text><rect x="180" y="60" width="130" height="70" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="245" y="90" text-anchor="middle" font-size="11">test</text><text x="245" y="106" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">i &lt; 15?</text><rect x="350" y="60" width="130" height="70" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="415" y="90" text-anchor="middle" font-size="11">body</text><text x="415" y="106" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">print(i)</text><rect x="510" y="60" width="120" height="70" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="570" y="90" text-anchor="middle" font-size="11">step</text><text x="570" y="106" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">i++</text><line x1="140" y1="95" x2="180" y2="95" stroke="currentColor" stroke-width="1.5"/><line x1="310" y1="95" x2="350" y2="95" stroke="currentColor" stroke-width="1.5"/><line x1="480" y1="95" x2="510" y2="95" stroke="currentColor" stroke-width="1.5"/><path d="M 570 130 C 400 180, 200 180, 245 130" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5" stroke-dasharray="5 4"/><text x="400" y="178" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">loop back while test is true; exit when false</text></svg>`,

  'itp-m5-counter': `<svg viewBox="0 0 640 100" aria-label="Animated loop counter"><title>Loop counter animation</title><rect x="10" y="25" width="500" height="50" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle cx="40" cy="50" r="9" fill="currentColor"/><text x="270" y="58" text-anchor="middle" font-size="13">i = 0</text><rect x="530" y="25" width="100" height="50" rx="8" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5"/><text x="580" y="55" text-anchor="middle" font-size="11">exit at 5</text></svg>`,

  'itp-m6': `<svg viewBox="0 0 640 210" aria-label="Function call diagram"><title>Call, arguments, return</title><rect x="10" y="60" width="150" height="90" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="85" y="90" text-anchor="middle" font-size="12">call</text><text x="85" y="108" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">max(3, 9)</text><text x="85" y="122" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">arguments in</text><rect x="230" y="60" width="180" height="90" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="320" y="90" text-anchor="middle" font-size="12">function body</text><text x="320" y="108" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">compare the two</text><text x="320" y="122" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">wrapped present</text><rect x="480" y="60" width="150" height="90" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="555" y="90" text-anchor="middle" font-size="12">return 9</text><text x="555" y="108" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">print or store</text><text x="555" y="122" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">else invisible</text><line x1="160" y1="105" x2="230" y2="105" stroke="currentColor" stroke-width="1.5"/><polygon points="230,99 242,105 230,111" fill="currentColor"/><line x1="410" y1="105" x2="480" y2="105" stroke="currentColor" stroke-width="1.5"/><polygon points="480,99 492,105 480,111" fill="currentColor"/></svg>`,

  'itp-m7': `<svg viewBox="0 0 640 220" aria-label="Arrays versus ArrayLists and dictionaries"><title>Fixed versus flexible storage</title><text x="110" y="25" text-anchor="middle" font-size="12">array[fixed]</text><g font-size="10"><rect x="30" y="40" width="40" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><rect x="70" y="40" width="40" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><rect x="110" y="40" width="40" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><rect x="150" y="40" width="40" height="30" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5" stroke-dasharray="4 3"/><text x="110" y="95" text-anchor="middle" fill="var(--color-fd-muted-foreground)">full? make a new one</text></g><text x="330" y="25" text-anchor="middle" font-size="12">ArrayList[grows]</text><rect x="260" y="40" width="140" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="330" y="60" text-anchor="middle" font-size="10">10 slots, then +more</text><text x="330" y="95" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">append beyond 10 -&gt; grows</text><text x="535" y="25" text-anchor="middle" font-size="12">dict{key:value}</text><rect x="465" y="40" width="140" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="535" y="60" text-anchor="middle" font-size="10">name -&gt; Ada</text><rect x="465" y="72" width="140" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="535" y="92" text-anchor="middle" font-size="10">id -&gt; 42</text><text x="535" y="120" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">lookup by key, not slot</text><text x="320" y="160" text-anchor="middle" font-size="11" fill="var(--color-fd-muted-foreground)">from math import factorial &mdash; borrow one tool, not the workshop</text><rect x="200" y="170" width="240" height="32" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="320" y="191" text-anchor="middle" font-size="11">multiplyNumbers(5, 8) -&gt; prints 40</text></svg>`,

  'itp-m8': `<svg viewBox="0 0 640 200" aria-label="Linear versus binary search"><title>Two searches</title><text x="160" y="20" text-anchor="middle" font-size="12">linear O(n): check each</text><g font-size="10"><rect x="40" y="35" width="40" height="28" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="60" y="53" text-anchor="middle">A</text><rect x="80" y="35" width="40" height="28" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="100" y="53" text-anchor="middle">B</text><rect x="120" y="35" width="40" height="28" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="140" y="53" text-anchor="middle">C</text><rect x="160" y="35" width="40" height="28" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="180" y="53" text-anchor="middle">D</text><rect x="200" y="35" width="40" height="28" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="220" y="53" text-anchor="middle">E</text><text x="160" y="85" text-anchor="middle" fill="var(--color-fd-muted-foreground)">1 -&gt; 2 -&gt; 3 -&gt; 4 -&gt; 5</text></g><text x="480" y="20" text-anchor="middle" font-size="12">binary O(log n): halve sorted</text><rect x="380" y="35" width="200" height="28" fill="none" stroke="currentColor" stroke-width="1.5"/><line x1="480" y1="35" x2="480" y2="63" stroke="currentColor" stroke-width="1.5"/><text x="430" y="53" text-anchor="middle" font-size="10">left</text><text x="530" y="53" text-anchor="middle" font-size="10">right</text><text x="480" y="85" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">keep half with target, repeat</text><rect x="40" y="110" width="560" height="60" rx="8" fill="none" stroke="var(--color-fd-ring)" stroke-width="1.5"/><text x="320" y="133" text-anchor="middle" font-size="11">call stack (stones): factorial(4) -&gt; factorial(3) -&gt; factorial(2) -&gt; base 1, then unwind 1-2-6-24</text><text x="320" y="152" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">no base = pile forever (stack overflow, like infinite loop)</text></svg>`,

  'itp-m8-halving': `<svg viewBox="0 0 640 90" aria-label="Animated binary search halving"><title>Halving animation</title><rect x="60" y="30" width="520" height="30" fill="none" stroke="currentColor" stroke-width="1.5"/><line x1="320" y1="30" x2="320" y2="60" stroke="currentColor" stroke-width="2.5"/><text x="320" y="78" text-anchor="middle" font-size="11">10 names, check middle</text></svg>`,

  'itp-m9': `<svg viewBox="0 0 640 210" aria-label="Pseudocode to flowchart to code to language choice"><title>Plan then pick</title><rect x="10" y="50" width="140" height="100" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="80" y="80" text-anchor="middle" font-size="11">pseudocode</text><text x="80" y="97" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">prompt, wait,</text><text x="80" y="111" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">compute, return</text><text x="80" y="125" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">no syntax</text><rect x="200" y="50" width="140" height="100" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="270" y="80" text-anchor="middle" font-size="11">flowchart</text><text x="270" y="97" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">boxes+arrows</text><text x="270" y="111" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">one function</text><rect x="390" y="50" width="240" height="100" rx="8" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="510" y="80" text-anchor="middle" font-size="11">pick language</text><text x="510" y="97" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">HTML/CSS: pages</text><text x="510" y="111" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">script: quick+portable</text><text x="510" y="125" text-anchor="middle" font-size="10" fill="var(--color-fd-muted-foreground)">general: Java/C++/Python</text><line x1="150" y1="100" x2="200" y2="100" stroke="currentColor" stroke-width="1.5"/><polygon points="200,94 212,100 200,106" fill="currentColor"/><line x1="340" y1="100" x2="390" y2="100" stroke="currentColor" stroke-width="1.5"/><polygon points="390,94 402,100 390,106" fill="currentColor"/></svg>`,
};

/**
 * Renders one of the lesson's own diagrams by id, with an optional caption.
 * Ids that are not in the ported set render nothing.
 */
export function LessonDiagram({ id, caption }: { id: string; caption?: string }) {
  const svg = DIAGRAMS[id];
  if (!svg) return null;

  return (
    <figure className="not-prose my-6">
      <div
        className="text-fd-foreground [&_svg]:h-auto [&_svg]:w-full"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      {caption ? (
        <figcaption className="mt-2 text-center text-xs text-fd-muted-foreground">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  );
}
